#include <iostream>
#include <time.h>
using namespace std;

void printRules()
{
    cout << "==============================================================================" << endl
         << endl;
    cout << "1. You have 7 attempts to Guess A Random Number ( 0 - 100 ) Generated By the Computer.\n\n";
    cout << "2. The Computer Tells You Wether You Need to go higher or lower.\n\n";
    cout << "3. Guess the Number and You Win!\n\n";
    cout << "4. Your Score is based on your Remaining Attempts\n\n";
    cout << "4. Have Fun!\n\n";
    cout << "==============================================================================" << endl;

    return;
}

int main()
{
    srand(time(NULL));

    int num = rand() % 101 + 1, Guess, Attempts = 7;

    printRules();

    for (; Attempts >= 0; Attempts--)
    {
        cout << "Remaining Attempts: " << Attempts << "\n\n";
        cout << "Enter Your Guess: ";
        cin >> Guess;

        if (Guess == num)
        {
            cout << "You Win!!\n\n";
            break;
        }
        else if (Guess < num)
            cout << "Higher! ;)\n\n";
        else
            cout << "Lower! :)\n\n";
    }

    if (Attempts)
        cout << "Well Done! Your Final Score: " << Attempts * 170 << endl
             << endl;
    else
        cout << "Better Luck Next Time! :(\n\n";

    return 0;
}
